- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables 
    COURSE: "Devops with AWS"
    DURATION: "120 hrs"
    TRAINER: "Siva"

  tasks:
  - name: print the varialbles1
    vars: #Task level variables
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "This is a {{ COURSE }} course, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

  - name: print the varialbles2
    ansible.builtin.debug:
      msg: "This is a {{ COURSE }} course, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"   