- name: Variables from files
  hosts: local
  connection: local
  vars_files: 
  - course.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "This is a {{ COURSE }} course, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
      