- name: Variables from files
  hosts: local
  connection: local
  vars_prompt: 
  - name: COURSE
    prompt: Please enter course name
    private: false # make it false if we want to display what user is typing
  - name: DURATION
    prompt: Please enter duration of the course
    private: false
  - name: TRAINER
    prompt: Please enter trainer name       
    private: false
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "This is a {{ COURSE }} course, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
      