- name: variables from Inventory
  hosts: local
  connection: local
  tasks: 
  - name: Print Course Information
    ansible.builtin.debug:
      msg: "This is a {{ COURSE }} course, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
      