- name: Variables from files
  hosts: web
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "This is a {{ COURSE }} course, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
      