- name: variables
  hosts: local
  connection: local
  vars_files: 
  - course.yaml
  vars:
    GREET: "PLAY"
  vars_prompt:
  - name: GREET
    prompt: Enter the value
    private: false
  tasks:
  - name: print the varialbles
    vars: 
      GREET: "TASKS"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

  #1.Command Line or args
  #2.Task Level
  #3.Files
  #4.Prompt
  #5.Play
  #6.Inventory
  #7.Roles