- name: Loops
  hosts: web
  connection: local
  tasks:
  - name: Print Name
    ansible.builtin.debug: #Module
      msg: "Hello {{ item }}" # Item is the reserved keyword
    loop:
    - Ramesh
    - Suresh
    - Rakesh    