- name: Filters
  hosts: local
  connection: local
  tasks:
  - name: Handling undefined vaiable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Vamshi')}}"
    
  - name: Convert string to list
    vars: 
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"
