---
- name: Install and start NGINX on RHEL
  hosts: webservers
  become: yes

  tasks:
    - name: Install NGINX
      yum:
        name: nginx
        state: present
      tags: install

    - name: Start NGINX
      systemd:
        name: nginx
        state: started
        enabled: yes
      tags: start
